# Configuration file for [`git-cliff`](https://github.com/orhun/git-cliff)
# See https://git-cliff.org/docs/configuration

[remote.github]
owner = "clowdhaus"
repo = "eksup"

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
# https://keats.github.io/tera/docs/#introduction
body = """\
{% set gh_link = "https://github.com/" ~ remote.github.owner ~ "/" ~ remote.github.repo %}\
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}]({{ gh_link }}/releases/tag/v{{ version | trim_start_matches(pat="v") }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]({{ gh_link }}/compare/{{ previous.version }}...HEAD)
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | title }}
    {% for commit in commits %}
        - {% if commit.scope %}[{{ commit.scope }}] {% endif %}{{ commit.message | upper_first | split(pat="\\n") | first }}\
    {% endfor %}
{% endfor %}\n
"""
trim = true
footer = """
"""

[git]
conventional_commits = true
filter_unconventional = false
commit_preprocessors = []
commit_parsers = [
    { message = "^[Ff]eat", group = "Features" },
    { message = "^[Ff]ix", group = "Bug Fixes" },
    { message = "^[Dd]oc", group = "Documentation" },
    { message = ".*\\b([Dd]eps|[Dd]ependencies|[Bb]ump)\\b", group = "Dependencies" },
    { message = "^[Pp]erf", group = "Performance" },
    { message = "^[Rr]efactor", group = "Refactor" },
    { message = ".*\\b([Ss]tyle|[Ff]mt|[Ff]ormat)\\b", group = "Styling" },
    { message = "^[Tt]est", group = "Testing" },
    { message = "^[Cc]hore", group = "Miscellaneous Tasks" },

    { message = ".*", group = "Other" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
skip_tags = "beta|alpha"
ignore_tags = "rc"
sort_commits = "newest"
